// @ts-check

// ref: https://docusaurus.io/docs/sidebar/items
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  noteSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

module.exports = sidebars;
