apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: node:20
          command:
            - /script/run.sh
          volumeMounts:
            - mountPath: /data/website
              name: website
            - mountPath: /script
              name: script
      volumes:
        - name: website
          hostPath:
            path: /data/website
            type: DirectoryOrCreate
        - name: script
          configMap:
            name: script
            defaultMode: 0777
